# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: QkUPyRUjiuZEc3wIMZbiLkjEdEhNaZrC
            client-secret: MkgfkQOk64KJPrnnSIktMsD5_6FIUXrTfd8-rMphqHxk3cc3JwOg3i3zIWgOCdgu

            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-5i1yoc5n.us.auth0.com/